# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'run_widgetvhyflR.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_runmode_widget(object):
    def setupUi(self, runmode_params_widget):
        if not runmode_params_widget.objectName():
            runmode_params_widget.setObjectName(u"runmode_params_widget")
        runmode_params_widget.resize(631, 481)
        self.stackedWidget = QStackedWidget(runmode_params_widget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(-1, -1, 631, 481))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.settingButton = QPushButton(self.page)
        self.settingButton.setObjectName(u"settingButton")
        self.settingButton.setGeometry(QRect(500, 30, 101, 41))
        self.label_6 = QLabel(self.page)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 30, 451, 41))
        font = QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.line = QFrame(self.page)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(30, 80, 571, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.groupBox = QGroupBox(self.page)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(270, 100, 331, 221))
        self.groupBox_2 = QGroupBox(self.page)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(30, 100, 231, 221))
        self.lcdBottleCounter = QLCDNumber(self.groupBox_2)
        self.lcdBottleCounter.setObjectName(u"lcdBottleCounter")
        self.lcdBottleCounter.setGeometry(QRect(10, 30, 91, 31))
        self.pushButton = QPushButton(self.groupBox_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(120, 30, 91, 31))
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(9, 10, 201, 20))
        self.label.setAlignment(Qt.AlignCenter)
        self.lcdSpeed = QLCDNumber(self.groupBox_2)
        self.lcdSpeed.setObjectName(u"lcdSpeed")
        self.lcdSpeed.setGeometry(QRect(10, 100, 91, 31))
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(9, 80, 211, 20))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 150, 211, 20))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.lcdAverageSpeed = QLCDNumber(self.groupBox_2)
        self.lcdAverageSpeed.setObjectName(u"lcdAverageSpeed")
        self.lcdAverageSpeed.setGeometry(QRect(10, 170, 91, 31))
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(110, 110, 81, 16))
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(110, 180, 81, 16))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.newSettingButton = QPushButton(self.page_2)
        self.newSettingButton.setObjectName(u"newSettingButton")
        self.newSettingButton.setGeometry(QRect(500, 30, 101, 41))
        self.settingComboBox = QComboBox(self.page_2)
        self.settingComboBox.setObjectName(u"settingComboBox")
        self.settingComboBox.setGeometry(QRect(30, 30, 451, 41))
        self.label_7 = QLabel(self.page_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 10, 171, 16))
        self.saveButton = QPushButton(self.page_2)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(360, 430, 111, 31))
        self.LevMax = QGroupBox(self.page_2)
        self.LevMax.setObjectName(u"LevMax")
        self.LevMax.setGeometry(QRect(30, 100, 101, 151))
        self.lev_max_plus = QPushButton(self.LevMax)
        self.lev_max_plus.setObjectName(u"lev_max_plus")
        self.lev_max_plus.setGeometry(QRect(20, 30, 61, 41))
        self.lev_max_plus.setCheckable(False)
        self.lev_max_minus = QPushButton(self.LevMax)
        self.lev_max_minus.setObjectName(u"lev_max_minus")
        self.lev_max_minus.setGeometry(QRect(20, 90, 61, 41))
        self.groupBox_3 = QGroupBox(self.page_2)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(240, 100, 361, 151))
        self.modelComboBox = QComboBox(self.groupBox_3)
        self.modelComboBox.setObjectName(u"modelComboBox")
        self.modelComboBox.setGeometry(QRect(10, 30, 341, 41))
        self.modelInfo = QLabel(self.groupBox_3)
        self.modelInfo.setObjectName(u"modelInfo")
        self.modelInfo.setGeometry(QRect(10, 80, 341, 61))
        self.modelInfo.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.groupBox_4 = QGroupBox(self.page_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(140, 100, 81, 321))
        self.lcdNumber = QLCDNumber(self.groupBox_4)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(10, 20, 61, 31))
        font1 = QFont()
        font1.setBold(False)
        font1.setWeight(50)
        self.lcdNumber.setFont(font1)
        self.lcdNumber.setDigitCount(3)
        self.lcdNumber.setProperty("value", 90.000000000000000)
        self.led_slider = QSlider(self.groupBox_4)
        self.led_slider.setObjectName(u"led_slider")
        self.led_slider.setGeometry(QRect(20, 70, 41, 231))
        self.led_slider.setMaximum(100)
        self.led_slider.setValue(89)
        self.led_slider.setOrientation(Qt.Vertical)
        self.cancelButton = QPushButton(self.page_2)
        self.cancelButton.setObjectName(u"cancelButton")
        self.cancelButton.setGeometry(QRect(490, 430, 111, 31))
        self.LevMax_3 = QGroupBox(self.page_2)
        self.LevMax_3.setObjectName(u"LevMax_3")
        self.LevMax_3.setGeometry(QRect(30, 270, 101, 151))
        self.lev_min_plus = QPushButton(self.LevMax_3)
        self.lev_min_plus.setObjectName(u"lev_min_plus")
        self.lev_min_plus.setGeometry(QRect(20, 30, 61, 41))
        self.lev_min_plus.setCheckable(False)
        self.lev_min_minus = QPushButton(self.LevMax_3)
        self.lev_min_minus.setObjectName(u"lev_min_minus")
        self.lev_min_minus.setGeometry(QRect(20, 90, 61, 41))
        self.line_2 = QFrame(self.page_2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(30, 80, 571, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.groupBox_5 = QGroupBox(self.page_2)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(240, 260, 361, 161))
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(runmode_params_widget)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(runmode_params_widget)
    # setupUi

    def retranslateUi(self, runmode_params_widget):
        runmode_params_widget.setWindowTitle(QCoreApplication.translate("runmode_params_widget", u"Form", None))
        self.settingButton.setText(QCoreApplication.translate("runmode_params_widget", u"Settings", None))
        self.label_6.setText(QCoreApplication.translate("runmode_params_widget", u"ETHEL SPUM V1", None))
        self.groupBox.setTitle(QCoreApplication.translate("runmode_params_widget", u"Statistics", None))
        self.groupBox_2.setTitle("")
        self.pushButton.setText(QCoreApplication.translate("runmode_params_widget", u"Reset", None))
        self.label.setText(QCoreApplication.translate("runmode_params_widget", u"Counter", None))
        self.label_2.setText(QCoreApplication.translate("runmode_params_widget", u"Speed", None))
        self.label_3.setText(QCoreApplication.translate("runmode_params_widget", u"Average speed", None))
        self.label_4.setText(QCoreApplication.translate("runmode_params_widget", u"Bottles/hour", None))
        self.label_5.setText(QCoreApplication.translate("runmode_params_widget", u"Bottles/hour", None))
        self.newSettingButton.setText(QCoreApplication.translate("runmode_params_widget", u"New Setting", None))
        self.label_7.setText(QCoreApplication.translate("runmode_params_widget", u"Setting", None))
        self.saveButton.setText(QCoreApplication.translate("runmode_params_widget", u"Save", None))
        self.LevMax.setTitle(QCoreApplication.translate("runmode_params_widget", u"Lev Max", None))
        self.lev_max_plus.setText(QCoreApplication.translate("runmode_params_widget", u"+", None))
        self.lev_max_minus.setText(QCoreApplication.translate("runmode_params_widget", u"-", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("runmode_params_widget", u"Model", None))
        self.modelInfo.setText(QCoreApplication.translate("runmode_params_widget", u"Model info", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("runmode_params_widget", u"LED", None))
        self.cancelButton.setText(QCoreApplication.translate("runmode_params_widget", u"Cancel", None))
        self.LevMax_3.setTitle(QCoreApplication.translate("runmode_params_widget", u"Lev Min", None))
        self.lev_min_plus.setText(QCoreApplication.translate("runmode_params_widget", u"+", None))
        self.lev_min_minus.setText(QCoreApplication.translate("runmode_params_widget", u"-", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("runmode_params_widget", u"Statistics", None))
    # retranslateUi

